apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-test 
  labels:
    name: mysql-test 
spec:
  replicas: 3 
  selector:
    name: mysql-test 
  template:
    metadata:
      labels:
        name: mysql-test 
    spec:
      containers:
      - name: mysql 
        image: maxwell/db:v1.0.1
        resources:
          limits:
            cpu: "1"
            memory: "2048Mi"
        ports:
        - containerPort: 3306

