apiVersion: v1
kind: Service
metadata:
  name: mysql-test 
  labels:
    name: mysql-test 
spec:
  ports:
    # the port that this service should serve on
  - port: 9306
    targetPort: 3306
    protocol: TCP
  selector:
    name: mysql-test 

