apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp-test 
  labels:
    name: webapp-test 
spec:
  replicas: 3 
  selector:
    name: webapp-test 
  template:
    metadata:
      labels:
        name: webapp-test 
    spec:
      containers:
      - name: gotest
        image: registry.test.com:5000/maxwell/webapp:v2 
        resources:
          limits:
            cpu: "1"
            memory: "2048Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9999
          initialDelaySeconds: 240
          timeoutSeconds: 5
        ports:
        - containerPort: 9999

