apiVersion: v1
kind: Service
metadata:
  name: webapp-test 
  labels:
    name: webapp-test 
spec:
  ports:
    # the port that this service should serve on
  - port: 9999
    targetPort: 9999
    protocol: TCP
  selector:
    name: webapp-test 

